build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 0

complexity:
  active: true
  ComplexCondition:
    active: true
    threshold: 3
  TooManyFunctions:
    active: true
    thresholdInFiles: 11

style:
  active: true
  MagicNumber:
    active: false
  NewLineAtEndOfFile:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 120

comments:
  active: true
  CommentOverPrivateFunction:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: "^(_|ignore.*|expected.*)$"

potential-bugs:
  active: true
  UnsafeCast:
    active: true
