build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1
    comments: 0

complexity:
  active: true
  TooManyFunctions:
    active: true
    threshold: 11

style:
  active: true
  MaxLineLength:
    active: true
    maxLineLength: 120

comments:
  active: true
  CommentOverPrivateFunction:
    active: true
    allowedPattern: "TODO|FIXME|Stub"

potential-bugs:
  active: true
  UnsafeCast:
    active: true
    exceptionClasses: "java.lang.ClassCastException"

formatting:
  active: false